### ISSUE TITLE
nrc80211 driver fail on Ubuntu 22.04 x86_64 5.15.0-112-generic

### ISSUE THREAD

**Issue by k3rn3Lp4n1cK** [Gateworks/nrc7292#3]
lsusb output
`Bus 001 Device 003: ID 2beb:0146 Gateworks GW16146-B`

Driver Loading Messages
`nrc80211 spi0.0: Failed to nrc_check_fw_ready`
`nrc80211 spi0.0: Failed to nrc_nw_start (-110)`
`nrc80211: probe of spi0.0 failed with error -110`

**Comment by Gateworks** [comment]
We do not support Gateworks miniPCIe adapters such as the GW16146 on boards other than Gateworks Single Board Computers.

If I had to hazard a guess perhaps there is something wrong with the ftdi-usb-spi USB-to-SPI driver (https://github.com/gateworks/ftdi-usb-spi) on your platform.
